version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-watch-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q26kcfv0s3z8"
s3_prefix = "cloud-watch-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
